auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: http://yishuihanxl.github.io/
url: http://yishuihanxl.github.io/
feed: /atom.xml
author_info: <a href="http://yishuihanxl.github.io/">YiShuiHanXL</a>
